### PR TITLE
Build on win64; add more maintainers.

### PR DESCRIPTION
**Pull request by cbrueffer**

### CODE REVIEW

**Comment by cbrueffer** [comment]
@conda-forge-admin, please rerender

**Comment by cbrueffer** [comment]
I'll look into OSX next.

**Comment by jdblischak** [comment]
@cbrueffer Do we know why this works now? libglu still isn't available for Windows or OSX:

https://github.com/conda-forge/libglu-feedstock

The package may install, but does it actually work? Maybe we should add a better test? We could adapt the first example from the vignette:

```
with(iris, plot3d(Sepal.Length, Sepal.Width, Petal.Length, 
                  type="s", col=as.numeric(Species)))
```

to

```
    - $R -e 'rgl::plot3d(iris$Sepal.Length, iris$Sepal.Width, iris$Petal.Length)'  # [not win]
    - "\"%R%\" -e \"'rgl::plot3d(iris$Sepal.Length, iris$Sepal.Width, iris$Petal.Length)'\""  # [win]
```

Note that the single quotes are required in the Unix version to avoid variable expansion of the `$`. I'm not sure if this will work on the Windows one, but I didn't want to mess with the intense quotation marks if I didn't have to.

**Comment by cbrueffer** [comment]
From my reading libglu is part of the Windows SDK, so it shouldn't need external installation.

**Comment by jdblischak** [comment]
> From my reading libglu is part of the Windows SDK, so it shouldn't need external installation.

@cbrueffer OK. I did some searching, but I don't know enough about this to confirm either way.

I did a quick test on my Windows machine, and I was able to install rgl from CRAN and create a 3d plot.

**Review by jdblischak — APPROVED** [review]

**Comment by cbrueffer** [comment]
Thanks @jdblischak and @bgruening for testing/committing!

**Pull request merged**
