### PR TITLE
Osx

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/r-rgl-feedstock/pull/23

This includes the update previously proposed in https://github.com/conda-forge/r-rgl-feedstock/pull/23 and adds fixes to get the OSX build working.

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
looks good, but needs a rebase.

**Comment by dbast** [comment]
The osx build tells:
```
This build of rgl does not include OpenGL functions.  Use
 rglwidget() to display results, e.g. via options(rgl.printRglwidget = TRUE).
```

What does that mean?

**Comment by izahn** [comment]
> This build of rgl does not include OpenGL functions

This happens because X11 is not available on the conda-forge CI infrastructure for osx: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=280685&view=logs&j=4b3757f9-99c5-5891-6c0c-93d7030cdf7d&t=f047df50-a233-5ae9-bf8f-c7dd8e5684ad&l=1214

For users this means that rgl graphics have to be displayed in a browser (including e.g., the browser built in to rstudio) instead of in a  dedicated X11 window.

There has been some effort get get XQuartz into conda-forge, but it seems to have stalled: https://github.com/conda-forge/staged-recipes/issues/2587

Some packages work-around by installing XQuartz with homebrew, e.g., https://github.com/conda-forge/ncview-feedstock/pull/4. My opinion is that for rgl the webGL viewer is perfectly serviceable, and lack of X11 on osx should not be a show-stopper.

**Pull request merged**
