### PR TITLE
Update

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by PertuyF** [comment]
@conda-forge-admin, please rerender

**Comment by PertuyF** [comment]
Fails on:

```
ERROR: loading failed
  unable to load shared object '$PREFIX/lib/R/library/rgl/libs/rgl.so':
  libGL.so.1: cannot open shared object file: No such file or directory
```

Looks related to [this issue](https://github.com/bioconda/bioconda-recipes/issues/489).
Could `mesa-libgl-devel` be required also while testing the package?

_____

**EDIT**: looks like anaconda uses `mesa-libgl-devel` version 11, but conda-forge `libglu` is stuck with version 9. May it be a problem of rgl linked to the wrong version of the lib using `cdt('mesa-libgl-devel')`?

```
$ conda search libgl
Loading channels: done
No match found for: libgl. Search: *libgl*
# Name                       Version           Build  Channel
libglu                         9.0.0               0  conda-forge
libglu                         9.0.0      h0c0bdc1_1  pkgs/main
libglu                         9.0.0      hf484d3e_1  pkgs/main
libglu                         9.0.0   hf484d3e_1000  conda-forge
libglu                         9.0.0      hfc679d8_0  conda-forge
mesa-libgl-cos6-i686          11.0.7      h8f8d5c3_0  pkgs/main
mesa-libgl-cos6-x86_64          11.0.7      h045e36e_0  pkgs/main
mesa-libgl-cos7-ppc64le          17.0.1               0  pkgs/main
mesa-libgl-cos7-ppc64le          17.2.3               0  pkgs/main
mesa-libgl-devel-cos6-i686          11.0.7      hec01f26_0  pkgs/main
mesa-libgl-devel-cos6-x86_64          11.0.7      h5a2c0ac_0  pkgs/main
mesa-libgl-devel-cos7-ppc64le          17.2.3               0  pkgs/main
mesa-libglapi-cos7-ppc64le          17.0.1               0  pkgs/main
mesa-libglapi-cos7-ppc64le          17.2.3               0  pkgs/main
```

**Comment by PertuyF** [comment]
@dbast do you think using [`yum_requirements.txt`](https://conda-forge.org/docs/maintainer/knowledge_base.html#core-dependency-tree-packages-cdt) with `mesa-libGL` could help passing this "** testing if installed package can be loaded" step?

Looking at the doc, I feel it could apply to this case.

**Comment by dbast** [comment]
@PertuyF Good idea... added mesa-libGL ... lets see how the build goes.

**Comment by PertuyF** [comment]
@dbast do you know if there is anything like [bioconda's extended container](https://bioconda.github.io/troubleshooting.html#using-the-extended-image) that can be used with conda-forge?

**Comment by dpryan79** [comment]
@dbast I can get this to build on Linux locally with the following:

```
diff --git a/recipe/build.sh b/recipe/build.sh
index 54e8f60..06d2b28 100644
--- a/recipe/build.sh
+++ b/recipe/build.sh
@@ -19,5 +19,7 @@ if [[ ${HOST} =~ .*darwin.* ]]; then
   export DYLD_FALLBACK_LIBRARY_PATH=${CONDA_BUILD_SYSROOT}/opt/X11/lib
 fi
 
+export LD_LIBRARY_PATH=${BUILD_PREFIX}/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64
+X11_CONFIGURE_ARGS="--x-includes=${PREFIX}/include --x-libraries=${BUILD_PREFIX}/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64"
 DISPLAY=${DISPLAY:-:0} \
   $R CMD INSTALL --build . --configure-args="--disable-ftgl ${X11_CONFIGURE_ARGS}"
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index c697cf7..2605d49 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -99,7 +99,7 @@ requirements:
 
 test:
   commands:
-    - $R -e "library('rgl')"           # [linux]
+    - LD_LIBRARY_PATH=${BUILD_PREFIX}/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64 $R -e "library('rgl')"           # [linux]
     - "\"%R%\" -e \"library('rgl')\""  # [win]
 
 about:
```

It's incredibly hacky (not sure why CONDA_BUILD_SYSROOT isn't set in the environment), but it works. Perhaps something like that would work?

**Comment by dpryan79** [comment]
@dbast I've taken the liberty of updating your PR with my proposed changes. If you don't object, we can merge this today then.

**Comment by dbast** [comment]
@dpryan79 The idea of that PR was to merge the AnacondaRecipes/master branch plus some additional updates to see how far this gets it building ... cool that you and @PertuyF found the last missing pieces ... build is now successful 👍 

Though I am not sure if really all the commits are required, but something to maybe look at later.

@dpryan79 Feel free to update / merge the branch.

**Comment by dpryan79** [comment]
It'll get almost all of the remaining R packages off the blacklist on bioconda, so merged :)

**Pull request merged**
